name: simple-voting
recipe: drupal11
config:
  webroot: web
  php: '8.3'
  database: mariadb:10.11

services:
  appserver:
    build_as_root:
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - chmod +x /usr/local/bin/composer

tooling:
  composer:
    service: appserver
    cmd: composer
  drush:
    service: appserver
    cmd: /app/vendor/bin/drush