<?php

declare(strict_types=1);

/**
 * @file
 * Provides a voting question entity type.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function simple_voting_theme(): array {
  return [
    'voting_question' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for voting question templates.
 *
 * Default template: voting-question.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the voting question information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_voting_question(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function simple_voting_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish voting questions.
      $storage = \Drupal::entityTypeManager()->getStorage('voting_question');
      $voting_question_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($voting_question_ids) as $voting_question) {
        $voting_question->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize voting questions.
      $storage = \Drupal::entityTypeManager()->getStorage('voting_question');
      $voting_question_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($voting_question_ids) as $voting_question) {
        $voting_question->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function simple_voting_user_predelete(UserInterface $account): void {
  // Delete voting questions that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('voting_question');
  $voting_question_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($voting_question_ids)
  );
}
